"""add user name fields

Revision ID: 6b880f4d5d79
Revises: 128ef09515c2
Create Date: 2026-08-28 23:31:27.693295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b880f4d5d79'
down_revision: Union[str, Sequence[str], None] = '128ef09515c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column(
            'first_name',
            sa.String(length=100),
            nullable=True
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'last_name',
            sa.String(length=100),
            nullable=True
        )
    )

    op.execute(
    """
    UPDATE users
    SET first_name = 'Admin',
        last_name = 'User'
    WHERE first_name IS NULL
       OR last_name IS NULL
    """
)

    op.alter_column(
        'users',
        'first_name',
        nullable=False
    )

    op.alter_column(
        'users',
        'last_name',
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
