"""add inventory number

Revision ID: 84578fbbc1de
Revises: e97f0f6730f6
Create Date: 2026-08-20 11:13:15.062090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84578fbbc1de'
down_revision: Union[str, Sequence[str], None] = 'e97f0f6730f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('inventory_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'books', ['inventory_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'inventory_number')
    # ### end Alembic commands ###
