"""add book active status

Revision ID: a7dc8f4cdfcf
Revises: c076619e3b1d
Create Date: 2026-08-26 15:08:09.051621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7dc8f4cdfcf'
down_revision: Union[str, Sequence[str], None] = 'c076619e3b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column(
        'books',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        )
    )

    op.alter_column(
        'books',
        'is_active',
        server_default=None
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'is_active')
    # ### end Alembic commands ###
