"""add phone number to borrowings

Revision ID: d9c36730fe71
Revises: 081a199d7ada
Create Date: 2026-08-22 08:55:17.754529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c36730fe71'
down_revision: Union[str, Sequence[str], None] = '081a199d7ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowings', sa.Column('phone_number', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowings', 'phone_number')
    # ### end Alembic commands ###
